language: node_js
node_js:
  - lts/*
cache:
  directories:
    - "node_modules"

# Default distribution. If left commented out,
# Travis will upgrade distros as needed
# dist: xenial
# os: linux

addons:
  postgresql: '12'
  apt:
    packages:
      # Ubuntu 16+ does not install this dependency by default, so we need to install it ourselves
      # Required for Cypress. https://docs.cypress.io/guides/guides/continuous-integration.html#Travis
      - libgconf-2-4
      - postgresql-12
      - postgresql-12-postgis-3

env:
  global:
    - NODE_ENV: test
    - PGPORT: 5433
    - PGVERSION: 12


services:
  - redis
  - postgresql

before_install:
  # Start the server and run it in background process
  - sudo cp /etc/postgresql/{9.6,12}/main/pg_hba.conf
  - sudo /etc/init.d/postgresql restart
  - psql -U postgres -c "create extension postgis"
  - psql -c "CREATE DATABASE streetmix_test;" -U postgres
  - npm install -g sequelize-cli
  - sequelize db:migrate

before_script:
  # Start the server and run it in background process
  - node index &

script:
  # Note: don't run `npm test` here directly, it's intended for local testing.
  - commitlint-travis
  - npm run jest
  - npm run lint
  - npm run cypress:run

after_script:
  # Send coverage reports generated by jest to Codecov
  - bash <(curl -s https://codecov.io/bash)
  # after all tests finish running we need
  # to kill all background jobs (like "npm start &")
  - kill $(jobs -p) || true

cache: npm
